# Generated by Django 6.0.3 on 2026-03-10 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoo',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='todoo',
            name='title',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
